name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rimbabazudewa/todo-actic-cahce
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s  --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v2
    - name : Move cache
      run: mv /cache/target .
    - name: Run migration
      run: diesel migration run
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    - name: Copy .env file
      run: cp .env.github .env
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
